Quickfix:
Updating component-closest to avoid  Error 
> Error: Cannot find module 'matches-selector'

Change in component-closest can be seen in 
https://github.com/component/closest/commit/aaadbecd8da2e808311cd7ad779c568a3209a9ff

As stated in package-json here: component-matches-selector is imported but matches-selector was used..
So fallback is needed.